from tkinter import ttk
import cx_Oracle
import tkinter as tk
global T
global tree

con = cx_Oracle.connect('bd083/bd083@//bd-dc.cs.tuiasi.ro:1539/orcl')
c = con.cursor()

def Quit():
    root.destroy()
def validateLogin():
    par1=username.get()
    print(par1)
    par2=password.get()
    print(par2)
    par3=ID_utilizator.get()
    oracle=("select nume_cumparator,telefon_cumparator, id_tranzactie from tranzactii where id_tranzactie="+par3+"")
    n=c.execute(oracle)
    for r in n:
        print(r)
    if(len(r))==3:
        asd1=r[2]
        asd2=r[1]
        asd3=r[0]
        if(int(par3)==int(asd1) and str(par2)==str(asd2) and str(par1)==str(asd3)):
            loginframe.pack_forget()
            mainframe.pack(fill='both', expand=1)
        else:
            tk.Label(loginframe,text="Date incorecte").place(x=30,y=100)
    else:
        tk.Label(loginframe, text="Date incorecte").place(x=30, y=100)
def insert_contnou():
    par5 = id_banca_var.get()
    par6 = numar_cont_var.get()
    par7 = depozit_var.get()
    id_banca_var.set("")
    numar_cont_var.set("")
    depozit_var.set("")
    oracle = ("insert into banca values(" + par5 + ",'" + par6 + "'," + par7 + ")")
    c.execute(oracle)
    con.commit()
    par1 = id_tranzactie_var.get()
    par2 = nume_cumparator_var.get()
    par3 = telefon_cumparator_var.get()
    par4 = banca_id_banca_var.get()
    id_tranzactie_var.set("")
    nume_cumparator_var.set("")
    telefon_cumparator_var.set("")
    banca_id_banca_var.set("")
    oracle1 = ("insert into tranzactii values(" + par1 + ",'" + par2 + "','" + par3 + "'," + par4 + " ) ")
    c.execute(oracle1)
    con.commit()
    tk.Label(framecontnou,text="ati fost introdus cu succes in baza de date").place(x=100,y=500)

def go_back():
    framecontnou.pack_forget()
    loginframe.pack(fill='both', expand=1)
def cont_nou():

    framecontnou.pack(fill='both', expand=1)
    loginframe.pack_forget()
    tk.Label(framecontnou, text="id_banca:").place(x=0, y=0)
    tk.Entry(framecontnou, textvariable=id_banca_var).place(x=90, y=0)
    tk.Label(framecontnou, text="numar_cont:").place(x=0, y=40)
    tk.Entry(framecontnou, textvariable=numar_cont_var).place(x=90, y=40)
    tk.Label(framecontnou, text="depozit:").place(x=0, y=80)
    tk.Entry(framecontnou, textvariable=depozit_var).place(x=90, y=80)
    tk.Label(framecontnou, text="id_tranzactie:").place(x=250, y=0)
    tk.Entry(framecontnou, textvariable=id_tranzactie_var).place(x=370, y=0)
    tk.Label(framecontnou, text="nume_cumparator:").place(x=250, y=40)
    tk.Entry(framecontnou, textvariable=nume_cumparator_var).place(x=370, y=40)
    tk.Label(framecontnou, text="telefon_cumparator:").place(x=250, y=80)
    tk.Entry(framecontnou, textvariable=telefon_cumparator_var).place(x=370, y=80)
    tk.Label(framecontnou, text="banca_id_banca:").place(x=250, y=120)
    tk.Entry(framecontnou, textvariable=banca_id_banca_var).place(x=370, y=120)
    tk.Label(framecontnou, text="(in acest camp se introduce id_banci de la campul 1)").place(x=500,y=120)
    tk.Button(framecontnou, text="inserati", command=insert_contnou).place(x=100, y=150)
    tk.Button(framecontnou,text="back",command=go_back).place(x=200,y=150)

def logare():

    loginframe.pack(fill='both', expand=1)
    usernameLabel = tk.Label(loginframe, text="User Name").grid(row=0, column=0)
    usernameEntry = tk.Entry(loginframe, textvariable=username).grid(row=0, column=1)
    passwordLabel = tk.Label(loginframe, text="Password").grid(row=1, column=0)
    passwordEntry = tk.Entry(loginframe, textvariable=password, show='*').grid(row=1, column=1)
    IDLabel = tk.Label(loginframe, text="ID Utilizator").grid(row=2, column=0)
    IDEntry = tk.Entry(loginframe, textvariable=ID_utilizator).grid(row=2, column=1)
    loginButton = tk.Button(loginframe, text="Login", command=validateLogin).grid(row=4, column=0)
    newButton = tk.Button(loginframe, text="Cont_nou",command=cont_nou).grid(row=4, column=1)

def afisare_locuri():
    c.execute('select l.id_loc,l.randul,l.coloana,l.pret,sa.nume from sala sa, loc l where l.sala_id_sala=id_sala order by id_loc asc')
    treeloc.heading('ID', text='ID')
    treeloc.heading('RAND', text='RAND')
    treeloc.heading('COLOANA', text='COLOANA')
    treeloc.heading('PRET', text='PRET')
    treeloc.heading('NUME_SALA', text='NUME_SALA')
    for i in treeloc.get_children():
        treeloc.delete(i)
    treerepartizare.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treebilete.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treeloc.insert('',tk.END,values=r)
    treeloc.place(x=100,y=0)

def afisare_Repartizare():
    c.execute('select d.actor, d.rol, s.nume from distributie d,spectacol s, repartizare r where r.spectacol_id_spectacol=s.id_spectacol and r.distributie_id_distributie=d.id_distributie order by s.nume asc')
    treerepartizare.heading('ACTOR', text='ACTOR')
    treerepartizare.heading('ROL', text='ROL')
    treerepartizare.heading('NUME_SPECTACOL', text='NUME_SPECTACOL')
    for i in treerepartizare.get_children():
        treerepartizare.delete(i)
    treeloc.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treebilete.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treerepartizare.insert('',tk.END,values=r)
    treerepartizare.place(x=100,y=0)

def afisare_banca():
    c.execute('select * from Banca order by id_banca asc')
    treebanca.heading('ID_BANCA',text='ID_BANCA')
    treebanca.heading('NUMAR_CONT', text='NUMAR_CONT')
    treebanca.heading('DEPOZIT', text='DEPOZIT')
    for i in treebanca.get_children():
        treebanca.delete(i)
    treeloc.place_forget()
    treerepartizare.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebilete.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treebanca.insert('',tk.END,values=r)
    treebanca.place(x=100,y=0)

def afisare_tranzactii():
    c.execute('select * from tranzactii order by id_tranzactie asc')
    treetranzactii.heading('ID_TRANZACTIE', text='ID_TRANZACTIE')
    treetranzactii.heading('NUME_CUMPARATOR', text='NUME_CUMPARATOR')
    treetranzactii.heading('TELEFON_CUMPARATOR', text='TELEFON_CUMPARATOR')
    treetranzactii.heading('BANCA_ID_BANCA', text='BANCA_ID_BANCA')
    for i in treetranzactii.get_children():
        treetranzactii.delete(i)
    treeloc.place_forget()
    treerepartizare.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treebilete.place_forget()
    for r in c:
        treetranzactii.insert('', tk.END, values=r)
    treetranzactii.place(x=100, y=0)

def afisare_orar():
    c.execute('select * from Orar order by id_orar asc')
    treeorar.heading('ID_ORAR', text='ID_ORAR')
    treeorar.heading('DATA', text='DATA')
    treeorar.heading('BILETE_DISPONIBILE', text='BILETE_DISPONIBILE')
    for i in treeorar.get_children():
        treeorar.delete(i)
    treeloc.place_forget()
    treerepartizare.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treebanca.place_forget()
    treebilete.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treeorar.insert('', tk.END, values=r)
    treeorar.place(x=100, y=0)

def afisare_Spectacol():
    c.execute('select s.id_spectacol, s.nume, s.autor, sa.nume||\'(\'||s.sala_id_sala||\')\', o.data||\'(\'||s.orar_id_orar||\')\' from orar o,sala sa, spectacol s where s.sala_id_sala=sa.id_sala and o.id_orar=s.orar_id_orar order by id_spectacol asc')
    treespectacol.heading('ID_SPECTACOL', text='ID_SPECTACOL')
    treespectacol.heading('NUME', text='NUME')
    treespectacol.heading('AUTOR', text='AUTOR')
    treespectacol.heading('NUME_SALA', text='NUME_SALA')
    treespectacol.heading('DATA_DESFASURARE', text='DATA_DESFASURARE')
    for i in treespectacol.get_children():
        treespectacol.delete(i)
    treeloc.place_forget()
    treerepartizare.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treebilete.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treespectacol.insert('', tk.END, values=r)
    treespectacol.place(x=100, y=0)

def afisare_Sala():
    c.execute('select * from Sala order by id_sala asc')
    treesala.heading('ID_SALA', text='ID_SALA')
    treesala.heading('NUME', text='NUME')
    for i in treesala.get_children():
        treesala.delete(i)
    treeloc.place_forget()
    treerepartizare.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treebilete.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treesala.insert('', tk.END, values=r)
    treesala.place(x=100, y=0)

def afisare_Distributie():
    c.execute('select * from Distributie order by id_distributie asc')
    treedistributie.heading('ID_DISTRIBUTIE', text='ID_DISTRIBUTIE')
    treedistributie.heading('ACTOR', text='ACTOR')
    treedistributie.heading('ROL', text='ROL')
    for i in treedistributie.get_children():
        treedistributie.delete(i)
    treeloc.place_forget()
    treerepartizare.place_forget()
    treesala.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treebilete.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treedistributie.insert('', tk.END, values=r)
    treedistributie.place(x=100, y=0)

def afisare_Bilet():
    c.execute('select t.nume_cumparator||\'(\'||b.tranzactii_id_tranzactie||\')\', s.nume, sa.nume,o.data||\'(\'||b.orar_id_orar||\')\' from orar o,tranzactii t, bilet b,spectacol s, sala sa where b.tranzactii_id_tranzactie=t.id_tranzactie and b.orar_id_orar=o.id_orar and s.orar_id_orar=o.id_orar and s.sala_id_sala=sa.id_sala order by t.nume_cumparator asc')
    treebilete.heading('nume_cumparator', text='nume_cumparator')
    treebilete.heading('nume_spectacol', text='nume_spectacol')
    treebilete.heading('nume_sala', text='nume_sala')
    treebilete.heading('data_spectacol', text='data_spectacol')
    for i in treebilete.get_children():
        treebilete.delete(i)
    treeloc.place_forget()
    treerepartizare.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treetranzactii.place_forget()
    for r in c:
        treebilete.insert('', tk.END, values=r)
    treebilete.place(x=100, y=0)

def stergere():
    treeloc.place_forget()
    treerepartizare.place_forget()
    treesala.place_forget()
    treedistributie.place_forget()
    treespectacol.place_forget()
    treeorar.place_forget()
    treebanca.place_forget()
    treetranzactii.place_forget()
    treebilete.place_forget()

def showinsert():
    insertframe.pack(fill='both', expand=1)
    framecontnou.pack_forget()
    loginframe.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    repartizareframe.pack_forget()
    deleteFrame.pack_forget()
    tk.Label(insertframe, text="randul:").place(x=530, y=300)
    tk.Label(insertframe, text="coloana:").place(x=530, y=340)
    tk.Label(insertframe, text="nume spectacol:").place(x=530, y=380)
    tk.Label(insertframe, text="Orasul:").place(x=530, y=420)
    tk.Label(insertframe, text="ID:").place(x=530, y=460)
    tk.Entry(insertframe, textvariable=randul_var).place(x=620, y=300)
    tk.Entry(insertframe, textvariable=coloana_var).place(x=620, y=340)
    tk.Entry(insertframe, textvariable=nume_spectacol_var).place(x=620, y=380)
    tk.Entry(insertframe, textvariable=nume_sala_var).place(x=620, y=420)
    tk.Entry(insertframe, textvariable=tranzactii_id_tranzactii_var).place(x=620, y=460)
    tk.Button(insertframe,text="inserati bilet",command=get_value).place(x=600,y=500)

def remove_value():
    par1=tranzactii_id_tranzactii_var.get()
    par2=orar_id_orar_var.get()
    tranzactii_id_tranzactii_var.set("")
    orar_id_orar_var.set("")
    oracle=("delete bilet where tranzactii_id_tranzactie="+par1+" and orar_id_orar="+par2+"")
    c.execute(oracle)
    con.commit()
    afisare_Bilet()

def showdelete():
    deleteFrame.pack(fill='both', expand=1)
    framecontnou.pack_forget()
    loginframe.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    repartizareframe.pack_forget()
    insertframe.pack_forget()
    tk.Label(deleteFrame, text="Numele_cumparator(ID):").place(x=530, y=300)
    tk.Label(deleteFrame, text="Data(ID):").place(x=530, y=340)
    tk.Entry(deleteFrame, textvariable=tranzactii_id_tranzactii_var).place(x=670, y=300)
    tk.Entry(deleteFrame, textvariable=orar_id_orar_var).place(x=670, y=340)
    tk.Button(deleteFrame, text="stergeti bilet", command=remove_value).place(x=600, y=380)

def stergere_sala():
    par1 = id_sala_var.get()
    sala_id_sala_var.set("")
    par2 = nume_sala_var.get()
    nume_sala_var.set("")
    oracle1=("delete loc where sala_id_sala="+par1+"")
    c.execute(oracle1)
    con.commit()
    oracle2=("delete spectacol where sala_id_sala="+par1+"")
    c.execute(oracle2)
    con.commit()
    oracle = ("delete sala where id_sala="+par1+" and nume='"+par2+"'")
    c.execute(oracle)
    con.commit()
    afisare_Sala()

def inserare_sala():
    par1=id_sala_var.get()
    id_sala_var.set("")
    par2=nume_sala_var.get()
    nume_sala_var.set("")
    oracle=("insert into sala values(id_sala_seq.nextval,'"+par2+"')")
    c.execute(oracle)
    con.commit()
    afisare_Sala()

def insertsali():
    saliframe.pack(fill='both', expand=1)
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    repartizareframe.pack_forget()
    deleteFrame.pack_forget()
    tk.Label(saliframe, text="id_sala:").place(x=0, y=480)
    tk.Entry(saliframe,textvariable=id_sala_var).place(x=60,y=480)
    tk.Label(saliframe,text="nume:").place(x=0,y=520)
    tk.Entry(saliframe,textvariable=nume_sala_var).place(x=60,y=520)
    tk.Button(saliframe,text="inserati",command=inserare_sala).place(x=30,y=550)
    tk.Button(saliframe,text="stergeti",command=stergere_sala).place(x=90,y=550)

def sterge_loc():
    par1 = id_loc_var.get()
    par2 = randul_var.get()
    par3 = coloana_var.get()
    par4 = pret_var.get()
    par5 = sala_id_sala_var.get()
    id_loc_var.set("")
    randul_var.set("")
    coloana_var.set("")
    pret_var.set("")
    sala_id_sala_var.set("")
    oracle = ("delete loc where id_loc="+par1+"and randul="+par2+"and coloana="+par3+"and pret="+par4+"and sala_id_sala="+par5+"")
    c.execute(oracle)
    con.commit()
    afisare_locuri()

def insert_loc():
    par1=id_loc_var.get()
    par2=randul_var.get()
    par3=coloana_var.get()
    par4=pret_var.get()
    par5=sala_id_sala_var.get()
    id_loc_var.set("")
    randul_var.set("")
    coloana_var.set("")
    pret_var.set("")
    sala_id_sala_var.set("")
    oracle=("insert into loc values(id_loc_seq.nextval,"+par2+","+par3+","+par4+","+par5+")")
    c.execute(oracle)
    con.commit()
    afisare_locuri()

def insertloc():
    locframe.pack(fill='both',expand=1)
    framecontnou.pack_forget()
    loginframe.pack_forget()
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    deleteFrame.pack_forget()
    repartizareframe.pack_forget()
    tk.Label(locframe, text="id_loc:").place(x=0, y=480)
    tk.Entry(locframe, textvariable=id_loc_var).place(x=90, y=480)
    tk.Label(locframe, text="randul:").place(x=0, y=520)
    tk.Entry(locframe, textvariable=randul_var).place(x=90, y=520)
    tk.Label(locframe, text="coloana:").place(x=0, y=560)
    tk.Entry(locframe, textvariable=coloana_var).place(x=90, y=560)
    tk.Label(locframe, text="pret:").place(x=0, y=600)
    tk.Entry(locframe, textvariable=pret_var).place(x=90, y=600)
    tk.Label(locframe, text="sala_id_sala:").place(x=0, y=640)
    tk.Entry(locframe, textvariable=sala_id_sala_var).place(x=90, y=640)
    tk.Button(locframe, text="inserati", command=insert_loc).place(x=30, y=660)
    tk.Button(locframe, text="stergeti", command=sterge_loc).place(x=90, y=660)

def sterge_spectacol():
    par1 = id_spectacol_var.get()
    par2 = nume_spectacol_var.get()
    par3 = autor_var.get()
    par4 = sala_spectacol_id_sala_var.get()
    par5 = orar_spectacol_id_orar_var.get()
    id_spectacol_var.set("")
    nume_spectacol_var.set("")
    autor_var.set("")
    sala_spectacol_id_sala_var.set("")
    orar_spectacol_id_orar_var.set("")
    oracle1=("delete repartizare where spectacol_id_spectacol="+par1+"")
    c.execute(oracle1)
    con.commit()
    oracle = ("delete spectacol where id_spectacol="+par1+"and nume='"+par2+"'and autor='"+par3+"'and sala_id_sala="+par4+"and orar_id_orar="+par5+"")
    c.execute(oracle)
    con.commit()
    afisare_Spectacol()

def insert_spectacol():
    par1=id_spectacol_var.get()
    par2=nume_spectacol_var.get()
    par3=autor_var.get()
    par4=sala_spectacol_id_sala_var.get()
    par5=orar_spectacol_id_orar_var.get()
    id_spectacol_var.set("")
    nume_spectacol_var.set("")
    autor_var.set("")
    sala_spectacol_id_sala_var.set("")
    orar_spectacol_id_orar_var.set("")
    oracle=("insert into spectacol values(id_spectacol_seq.nextval,'"+par2+"','"+par3+"',"+par4+","+par5+")")
    c.execute(oracle)
    con.commit()
    afisare_Spectacol()

def insertspectacol():
    spectacolframe.pack(fill='both', expand=1)
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    deleteFrame.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    repartizareframe.pack_forget()
    tk.Label(spectacolframe, text="id_spectacol:").place(x=0, y=480)
    tk.Entry(spectacolframe, textvariable=id_spectacol_var).place(x=90, y=480)
    tk.Label(spectacolframe, text="nume_spectacol:").place(x=0, y=520)
    tk.Entry(spectacolframe, textvariable=nume_spectacol_var).place(x=90, y=520)
    tk.Label(spectacolframe, text="autor_spectacol:").place(x=0, y=560)
    tk.Entry(spectacolframe, textvariable=autor_var).place(x=90, y=560)
    tk.Label(spectacolframe, text="sala_id_sala:").place(x=0, y=600)
    tk.Entry(spectacolframe, textvariable=sala_spectacol_id_sala_var).place(x=90, y=600)
    tk.Label(spectacolframe, text="orar_id_orar:").place(x=0, y=640)
    tk.Entry(spectacolframe, textvariable=orar_spectacol_id_orar_var).place(x=90, y=640)
    tk.Button(spectacolframe, text="inserati", command=insert_spectacol).place(x=30, y=660)
    tk.Button(spectacolframe, text="stergeti", command=sterge_spectacol).place(x=90, y=660)

def sterge_distributie():
    par1 = id_distributie_var.get()
    par2 = actor_var.get()
    par3 = rol_var.get()
    id_distributie_var.set("")
    actor_var.set("")
    rol_var.set("")
    oracle = ("delete distributie where id_distributie="+par1+" and actor='"+par2+"'and rol='"+par3+"'")
    c.execute(oracle)
    con.commit()
    afisare_Distributie()

def insert_distributie():
    par1=id_distributie_var.get()
    par2=actor_var.get()
    par3=rol_var.get()
    id_distributie_var.set("")
    actor_var.set("")
    rol_var.set("")
    oracle=("insert into distributie values(id_distributie_seq.nextval,'"+par2+"','"+par3+"')")
    c.execute(oracle)
    con.commit()
    afisare_Distributie()

def insertdistributie():
    distributieframe.pack(fill='both', expand=1)
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    bancaframe.pack_forget()
    deleteFrame.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    repartizareframe.pack_forget()
    tk.Label(distributieframe, text="id_distributie:").place(x=0, y=480)
    tk.Entry(distributieframe, textvariable=id_distributie_var).place(x=90, y=480)
    tk.Label(distributieframe, text="actor:").place(x=0, y=520)
    tk.Entry(distributieframe, textvariable=actor_var).place(x=90, y=520)
    tk.Label(distributieframe, text="rol:").place(x=0, y=560)
    tk.Entry(distributieframe, textvariable=rol_var).place(x=90, y=560)
    tk.Button(distributieframe, text="inserati",command=insert_distributie).place(x=30, y=590)
    tk.Button(distributieframe, text="stergeti",command=sterge_distributie).place(x=90, y=590)

def sterge_orar():
    par1 = id_orar_var.get()
    id_orar_var.set("")
    oracle1=("delete bilet where orar_id_orar="+par1+"")
    c.execute(oracle1)
    con.commit()
    oracle = ("delete orar where id_orar="+par1+"")
    c.execute(oracle)
    con.commit()
    afisare_orar()

def insert_orar():
    par1=id_orar_var.get()
    par2=data_orar_var.get()
    par3=bilete_disponibile_var.get()
    id_orar_var.set("")
    data_orar_var.set("")
    bilete_disponibile_var.set("")
    oracle=("insert into orar values(id_orar_seq.nextval,to_date('"+par2+"','hh24:mi, DD MON, YYYY'),"+par3+")")
    c.execute(oracle)
    con.commit()
    afisare_orar()

def insertorar():
    orarframe.pack(fill='both', expand=1)
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    tranzactiiframe.pack_forget()
    spectacolframe.pack_forget()
    repartizareframe.pack_forget()
    deleteFrame.pack_forget()
    tk.Label(orarframe, text="id_orar:").place(x=0, y=480)
    tk.Entry(orarframe, textvariable=id_orar_var).place(x=100, y=480)
    tk.Label(orarframe, text="data:").place(x=0, y=520)
    tk.Label(orarframe,text="(hh:mm, DD MON,YYYY)").place(x=220,y=520)
    tk.Entry(orarframe, textvariable=data_orar_var).place(x=100, y=520)
    tk.Label(orarframe, text="bilete_disponibile:").place(x=0, y=560)
    tk.Entry(orarframe, textvariable=bilete_disponibile_var).place(x=100, y=560)
    tk.Button(orarframe, text="inserati",command=insert_orar).place(x=30, y=590)
    tk.Button(orarframe, text="stergeti", command=sterge_loc).place(x=90, y=590)

def sterge_tranzactii():
    par1 = id_tranzactie_var.get()
    par2 = nume_cumparator_var.get()
    par3 = telefon_cumparator_var.get()
    par4 = banca_id_banca_var.get()
    id_tranzactie_var.set("")
    nume_cumparator_var.set("")
    telefon_cumparator_var.set("")
    banca_id_banca_var.set("")
    oracle1=("delete bilet where tranzactii_id_tranzactie="+par1+"")
    oracle2=("delete banca where id_banca="+par4+"")
    c.execute(oracle1)
    con.commit()
    oracle = ("delete tranzactii where id_tranzactie="+par1+"and nume_cumparator='"+par2+"' and telefon_cumparator='"+par3+"' and banca_id_banca="+par4+"")
    c.execute(oracle)
    con.commit()
    c.execute(oracle2)
    con.commit()
    afisare_tranzactii()

def insert_tranzactii():
    par1 = id_tranzactie_var.get()
    par2 = nume_cumparator_var.get()
    par3 = telefon_cumparator_var.get()
    par4 = banca_id_banca_var.get()
    id_tranzactie_var.set("")
    nume_cumparator_var.set("")
    telefon_cumparator_var.set("")
    banca_id_banca_var.set("")
    oracle = ("insert into tranzactii values(id_tranzactie_seq.nextval,'" + par2 + "','" + par3 + "'," + par4 + " ) ")
    c.execute(oracle)
    con.commit()
    afisare_tranzactii()

def inserttranzactii():
    tranzactiiframe.pack(fill='both', expand=1)
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    repartizareframe.pack_forget()
    tk.Label(tranzactiiframe, text="id_tranzactie:").place(x=0, y=480)
    tk.Entry(tranzactiiframe, textvariable=id_tranzactie_var).place(x=110, y=480)
    tk.Label(tranzactiiframe, text="nume_cumparator:").place(x=0, y=520)
    tk.Entry(tranzactiiframe, textvariable=nume_cumparator_var).place(x=110, y=520)
    tk.Label(tranzactiiframe, text="telefon_cumparator:").place(x=0, y=560)
    tk.Entry(tranzactiiframe, textvariable=telefon_cumparator_var).place(x=110, y=560)
    tk.Label(tranzactiiframe, text="banca_id_banca:").place(x=0, y=600)
    tk.Entry(tranzactiiframe, textvariable=banca_id_banca_var).place(x=110, y=600)
    tk.Button(tranzactiiframe, text="inserati", command=insert_tranzactii).place(x=30, y=660)
    tk.Button(tranzactiiframe, text="stergeti", command=sterge_tranzactii).place(x=90, y=660)

def insert_banca():
    par1=id_banca_var.get()
    par2=numar_cont_var.get()
    par3=depozit_var.get()
    id_banca_var.set("")
    numar_cont_var.set("")
    depozit_var.set("")
    oracle=("insert into banca values(id_banca_seq.nextval,'"+par2+"',"+par3+")")
    c.execute(oracle)
    con.commit()
    afisare_banca()

def insertbanca():
    bancaframe.pack(fill='both', expand=1)
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    deleteFrame.pack_forget()
    repartizareframe.pack_forget()
    tk.Label(bancaframe, text="id_banca:").place(x=0, y=480)
    tk.Entry(bancaframe, textvariable=id_banca_var).place(x=90, y=480)
    tk.Label(bancaframe, text="numar_cont:").place(x=0, y=520)
    tk.Entry(bancaframe, textvariable=numar_cont_var).place(x=90, y=520)
    tk.Label(bancaframe, text="depozit:").place(x=0, y=560)
    tk.Entry(bancaframe, textvariable=depozit_var).place(x=90, y=560)
    tk.Button(bancaframe, text="inserati",command=insert_banca).place(x=30, y=590)

def sterge_repartizare():
    par1 = spectacol_id_spectacol_var.get()
    par2 = distributie_id_distributie_var.get()
    spectacol_id_spectacol_var.set("")
    distributie_id_distributie_var.set("")
    oracle = ("delete repartizare where spectacol_id_spectacol="+par1+" and distributie_id_distributie="+par2+"")
    c.execute(oracle)
    con.commit()
    afisare_Repartizare()

def insert_repartizare():
    par1 = spectacol_id_spectacol_var.get()
    par2 = distributie_id_distributie_var.get()
    spectacol_id_spectacol_var.set("")
    distributie_id_distributie_var.set("")
    oracle = ("insert into repartizare values(" + par1 + "," + par2 + ")")
    c.execute(oracle)
    con.commit()
    afisare_Repartizare()

def insertrepartizare():
    repartizareframe.pack(fill='both',expand=1)
    insertframe.pack_forget()
    deleteFrame.pack_forget()
    deleteFrame.pack_forget()
    saliframe.pack_forget()
    locframe.pack_forget()
    distributieframe.pack_forget()
    bancaframe.pack_forget()
    tranzactiiframe.pack_forget()
    orarframe.pack_forget()
    spectacolframe.pack_forget()
    tk.Label(repartizareframe, text="spectacol_id_spectacol:").place(x=0, y=480)
    tk.Entry(repartizareframe, textvariable=spectacol_id_spectacol_var).place(x=135, y=480)
    tk.Label(repartizareframe, text="distributie_id_distributie:").place(x=0, y=520)
    tk.Entry(repartizareframe, textvariable=distributie_id_distributie_var).place(x=135, y=520)
    tk.Button(repartizareframe, text="inserati", command=insert_repartizare).place(x=30, y=550)
    tk.Button(repartizareframe, text="stergeti", command=sterge_repartizare).place(x=90, y=550)

def get_value():
   par1=randul_var.get()
   par2=coloana_var.get()
   par3=nume_spectacol_var.get()
   par4=nume_sala_var.get()
   par5=tranzactii_id_tranzactii_var.get()
   randul_var.set("")
   coloana_var.set("")
   nume_spectacol_var.set("")
   nume_sala_var.set("")
   tranzactii_id_tranzactii_var.set("")
   oracle = ("insert into bilet values((select o.id_orar from orar o, sala sa, spectacol s, loc l where o.id_orar=s.orar_id_orar and s.sala_id_sala=sa.id_sala and l.sala_id_sala=sa.id_sala and l.coloana="+par2+" and l.randul="+par1+" and sa.nume='"+par4+"' and s.nume='"+par3+"'),"+par5+")")
   oracle1=("update banca set depozit=depozit-(select pret from loc, sala where randul="+par1+" and coloana="+par2+" and sala.nume='"+par4+"' and sala.id_sala=sala_id_sala) where id_banca=(select banca_id_banca from tranzactii where id_tranzactie="+par5+")")
   c.execute(oracle)
   con.commit()
   c.execute(oracle1)
   con.commit()

if __name__ == '__main__':

    root = tk.Tk()
    root.geometry("1120x700")
    root.resizable(False,False)
    framecontnou=tk.Frame(root)
    insertframe=tk.Frame(root)
    deleteFrame=tk.Frame(root)
    saliframe=tk.Frame(root)
    locframe=tk.Frame(root)
    distributieframe=tk.Frame(root)
    bancaframe=tk.Frame(root)
    tranzactiiframe=tk.Frame(root)
    orarframe=tk.Frame(root)
    spectacolframe=tk.Frame(root)
    repartizareframe=tk.Frame(root)
    loginframe=tk.Frame(root)
    mainframe=tk.Frame(root)
    username = tk.StringVar()
    password = tk.StringVar()
    id_sala_var = tk.StringVar()
    nume_sala_var = tk.StringVar()
    id_loc_var = tk.StringVar()
    randul_var = tk.StringVar()
    coloana_var=tk.StringVar()
    pret_var=tk.StringVar()
    sala_id_sala_var=tk.StringVar()
    id_distributie_var=tk.StringVar()
    actor_var=tk.StringVar()
    rol_var=tk.StringVar()
    spectacol_id_spectacol_var=tk.StringVar()
    distributie_id_distributie_var=tk.StringVar()
    id_spectacol_var=tk.StringVar()
    nume_spectacol_var=tk.StringVar()
    autor_var=tk.StringVar()
    sala_spectacol_id_sala_var=tk.StringVar()
    orar_id_orar_var=tk.StringVar()
    id_orar_var=tk.StringVar()
    data_orar_var=tk.StringVar()
    bilete_disponibile_var=tk.StringVar()
    orar_spectacol_id_orar_var=tk.StringVar()
    tranzactii_id_tranzactii_var=tk.StringVar()
    id_tranzactie_var=tk.StringVar()
    nume_cumparator_var=tk.StringVar()
    telefon_cumparator_var=tk.StringVar()
    banca_id_banca_var=tk.StringVar()
    id_banca_var=tk.StringVar()
    numar_cont_var=tk.StringVar()
    depozit_var=tk.StringVar()
    ID_utilizator=tk.StringVar()
    #TREE

    coloaneloc = ('ID', 'RAND', 'COLOANA', 'PRET', 'NUME_SALA')
    treeloc = ttk.Treeview(root, columns=coloaneloc, show='headings')
#
    coloanerepartizare = ('ACTOR', 'ROL','NUME_SPECTACOL')
    treerepartizare = ttk.Treeview(root, columns=coloanerepartizare, show='headings')
#
    coloanebanca = ('ID_BANCA', 'NUMAR_CONT', 'DEPOZIT')
    treebanca = ttk.Treeview(root, columns=coloanebanca, show='headings')
#
    coloanetranzactii = ('ID_TRANZACTIE', 'NUME_CUMPARATOR','TELEFON_CUMPARATOR','BANCA_ID_BANCA')
    treetranzactii = ttk.Treeview(root, columns=coloanetranzactii, show='headings')
#
    coloaneorar = ('ID_ORAR', 'DATA', 'BILETE_DISPONIBILE')
    treeorar = ttk.Treeview(root, columns=coloaneorar, show='headings')
#
    coloanespectacol = ('ID_SPECTACOL', 'NUME','AUTOR','NUME_SALA','DATA_DESFASURARE')
    treespectacol = ttk.Treeview(root, columns=coloanespectacol, show='headings')
#
    coloanedistributie = ('ID_DISTRIBUTIE', 'ACTOR', 'ROL')
    treedistributie = ttk.Treeview(root, columns=coloanedistributie, show='headings')
#
    coloanebilete = ('nume_cumparator', 'nume_spectacol','nume_sala','data_spectacol')
    treebilete = ttk.Treeview(root, columns=coloanebilete, show='headings')
#
    coloanesala = ('ID_SALA', 'NUME')
    treesala = ttk.Treeview(root, columns=coloanesala, show='headings')

    ButtonLocuri=tk.Button(root,text="afisare locuri",command=afisare_locuri,padx=10,pady=0).place(x=0,y=0)
    ButtonBanca = tk.Button(root, text="afisare banci", command=afisare_banca,padx=10,pady=0).place(x=0,y=40)
    ButtonTranzactii = tk.Button(root, text="afisare Tranzactii", command=afisare_tranzactii, padx=0, pady=0).place(x=0, y=80)
    ButtonOrar = tk.Button(root, text="afisare orar", command=afisare_orar, padx=15, pady=0).place(x=0, y=120)
    ButtonSala=tk.Button(root,text="afisare Sala",command=afisare_Sala,padx=15,pady=0).place(x=0,y=160)
    ButtonSpectacol = tk.Button(root, text="afisare Spectacol", command=afisare_Spectacol,padx=0,pady=0).place(x=0,y=200)
    ButtonDistributie=tk.Button(root,text="afisare Distributii",command=afisare_Distributie,padx=0,pady=0).place(x=0,y=240)
    ButtonRepartizare=tk.Button(root,text="afisare Repartizari",command=afisare_Repartizare,padx=0,pady=0).place(x=0,y=280)
    ButtonBilete = tk.Button(root, text="afisare Bilete", command=afisare_Bilet, padx=0, pady=0).place(x=0, y=320)
    ButtonClear = tk.Button(root, text="stergere", command=stergere, padx=10, pady=0).place(x=0,y=360)
    ButtonStergere = tk.Button(root, text="Stergere", command=showdelete, padx=10, pady=0).place(x=670, y=240)
    ButtonInsert = tk.Button(root, text="Inserare", command=showinsert, padx=10, pady=0).place(x=580, y=240)

    #insert in tabele

    tk.Label(root,text="Unde doriti sa inserati sau stergeti?").place(x=0,y=400)
    LocButton = tk.Button(root, text='Loc',command=insertloc).place(x=0, y=440)
    SalaButton = tk.Button(root, text='Sala',command=insertsali).place(x=40, y=440)
    SpectacolButton = tk.Button(root, text='Spectacol',command=insertspectacol).place(x=80, y=440)
    DistributieButton = tk.Button(root, text='Distributie',command=insertdistributie).place(x=150, y=440)
    OrarButton = tk.Button(root, text='Orar',command=insertorar).place(x=225, y=440)
    BancaButton = tk.Button(root, text='Banca',command=insertbanca).place(x=270, y=440)
    TranzactiiButton = tk.Button(root, text='Tranzactii',command=inserttranzactii).place(x=320, y=440)
    RepartizareButton = tk.Button(root, text='Repartizare',command=insertrepartizare).place(x=390, y=440)

    #Delete
    root.mainloop()